const LOGIN_FORM_FAILED = -101;
const PASSWORD_NOT_MATCHED = -102;
const USER_NOT_FOUND = -103;
const NO_PERMISSION = -104;

const CREATE_PRODUCT_FAILED = -201;
const PRODUCT_NOT_FOUND = -202;
const UPDATE_PRODUCT_FAILED = -203;

const CATEGORY_NOT_FOUND = -301;
const PRODUCTLINE_NOT_FOUND = -302;

module.exports = {
    ErrorTypes: {
        LOGIN_FORM_FAILED,
        PASSWORD_NOT_MATCHED,
        USER_NOT_FOUND,
        NO_PERMISSION,

        CREATE_PRODUCT_FAILED,
        PRODUCT_NOT_FOUND,
        UPDATE_PRODUCT_FAILED,

        CATEGORY_NOT_FOUND,
        PRODUCTLINE_NOT_FOUND
    }
};
