const LOGIN_FORM_FAILED = -101;
const PASSWORD_NOT_MATCHED = -102;
const USER_NOT_FOUND = -103;
const NO_PERMISSION = -104;

const INVALID_PRODUCT_DATA = -201;
const PRODUCT_NOT_FOUND = -202;
const UPDATE_PRODUCT_FAILED = -203;
const PRODUCT_QUANTITY_NOT_ENOUGH = -204;

const CATEGORY_NOT_FOUND = -301;
const CATEGORY_ALREADY_EXIST = -302;
const INVALID_CATEGORY_DATA = -304;

const PRODUCTLINE_NOT_FOUND = -402;
const INVALID_PRODUCTLINE_DATA = -403;
const PRODUCTLINE_NOT_UNIQUE = -404;

const INVALID_ORDER_DATA = -501;

const INVALID_QUERY_DATA = -601;

const IMAGE_NOT_FOUND = -701;

module.exports = {
    ErrorTypes: {
        LOGIN_FORM_FAILED,
        PASSWORD_NOT_MATCHED,
        USER_NOT_FOUND,
        NO_PERMISSION,

        INVALID_PRODUCT_DATA,
        PRODUCT_NOT_FOUND,
        UPDATE_PRODUCT_FAILED,
        PRODUCT_QUANTITY_NOT_ENOUGH,

        CATEGORY_NOT_FOUND,
        CATEGORY_ALREADY_EXIST,
        INVALID_CATEGORY_DATA,

        PRODUCTLINE_NOT_FOUND,
        INVALID_PRODUCTLINE_DATA,
        PRODUCTLINE_NOT_UNIQUE,

        INVALID_ORDER_DATA,
        IMAGE_NOT_FOUND,
        INVALID_QUERY_DATA
    }
};
